import 'package:whitenoise/ui/core/themes/src/colors.dart';

const fallbackColorsExt = AppColorsThemeExt(
  primary: LightAppColors.primary,
  neutral: LightAppColors.neutral,
  success: LightAppColors.lime,
  warning: LightAppColors.warning,
  tertiary: LightAppColors.tertiary,
  secondary: LightAppColors.secondary,
  neutralVariant: LightAppColors.neutralVariant,
  baseChat2: LightAppColors.baseChat2,
  primaryForeground: LightAppColors.primaryForeground,
  secondaryForeground: LightAppColors.secondaryForeground,
  mutedForeground: LightAppColors.mutedForeground,
  baseMuted: LightAppColors.baseMuted,
  textDefaultSecondary: LightAppColors.textDefaultSecondary,
  destructive: LightAppColors.destructive,
  baseChat: LightAppColors.baseChat,
  teal200: LightAppColors.teal200,
  teal600: LightAppColors.teal600,
  rose: LightAppColors.rose,
  lime: LightAppColors.lime,
  appBarBackground: LightAppColors.appBarBackground,
  appBarForeground: LightAppColors.appBarForeground,
  bottomSheetBarrier: LightAppColors.bottomSheetBarrier,
  link: LightAppColors.link,
  border: LightAppColors.border,
  avatarSurface: LightAppColors.avatarSurface,
  solidPrimary: LightAppColors.solidPrimary,
  input: LightAppColors.input,
  meChatBubble: LightAppColors.meChatBubble,
  contactChatBubble: LightAppColors.contactChatBubble,
  meChatBubbleText: LightAppColors.meChatBubbleText,
  contactChatBubbleText: LightAppColors.contactChatBubbleText,
  overlay: LightAppColors.overlay,
  surface: LightAppColors.surface,
);
