// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Account> createIdentity({required Whitenoise whitenoise}) =>
    RustLib.instance.api.crateApiAccountsCreateIdentity(whitenoise: whitenoise);

Future<Account> login({
  required Whitenoise whitenoise,
  required String nsecOrHexPrivkey,
}) => RustLib.instance.api.crateApiAccountsLogin(
  whitenoise: whitenoise,
  nsecOrHexPrivkey: nsecOrHexPrivkey,
);

Future<void> logout({
  required Whitenoise whitenoise,
  required Account account,
}) => RustLib.instance.api.crateApiAccountsLogout(
  whitenoise: whitenoise,
  account: account,
);

Future<Account> updateActiveAccount({
  required Whitenoise whitenoise,
  required Account account,
}) => RustLib.instance.api.crateApiAccountsUpdateActiveAccount(
  whitenoise: whitenoise,
  account: account,
);
